### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by sakas23** [cnotin/SplunkWhisperer2#3]
Hello everybody,

I have an issue trying to run the python script.

![Screenshot_4](https://user-images.githubusercontent.com/57067833/96741053-19acab00-13ca-11eb-86ee-9d14894690b1.png)

Any help is much appreciated.

**Comment by cnotin** [comment]
You're trying to run a Python2 script with Python3 interpreter!
Its remote version was ported to Python 3 recently though

**Comment by sakas23** [comment]
> 
> 
> You're trying to run a Python2 script with Python3 interpreter!
> Its remote version was ported to Python 3 recently though

If i try with python2 it says no module requests found

**Comment by cnotin** [comment]
Because you need the "requests" module as shown in the requirements.txt file ;)
python2 -m pip install -r requirements.txt
