### ISSUE TITLE
Read Timeout error 

### ISSUE THREAD

**Issue by ishikawa-riva** [cnotin/SplunkWhisperer2#5]
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <messages>
    <msg type="ERROR">Unexpected error downloading update: Read Timeout</msg>
  </messages>
</response>

**Comment by cnotin** [comment]
https://community.splunk.com/t5/Getting-Data-In/why-does-splunk-timeout-when-I-try-to-manually-load-an-app/m-p/67896
Looks like splunk cannot reach your server to download the app. Certainly an error in your parameters
